import type { Metadata } from "next";
import {Poppins} from "next/font/google";
import "./globals.scss";
import { Providers } from "./Providers";

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: [ '300' ,'500',  '600','700'],
  variable: '--Poppins'
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${poppins.className}`}>
        <Providers>
        {children}
        </Providers>
      </body>
    </html>
  );
}
